# Generated by Django 5.0.6 on 2024-06-14 00:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodzone',
            name='image_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='floodzone',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
