# Generated by Django 5.0.6 on 2024-06-15 22:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzoneapp', '0002_alter_floodzone_image_url_alter_floodzone_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
