# Generated by Django 5.0.6 on 2024-06-15 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzoneapp', '0003_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='location',
        ),
        migrations.AddField(
            model_name='tweet',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
