# Generated by Django 5.0.6 on 2024-06-26 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzoneapp', '0004_remove_tweet_location_tweet_geom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(dim=models.FloatField(blank=True, null=True), srid=4326, verbose_name=models.FloatField(blank=True, null=True)),
        ),
    ]
